---
- name: Restart NSLCD
  service:
    name: nslcd
    state: restarted

- name: Validate SSH config
  command: sshd -t
  notify: Reload SSH daemon

- name: Reload SSH daemon
  service:
    name: sshd
    state: reloaded

- name: Update PAM configuration
  command: >
    pam-auth-update
    --enable pam-param mkhomedir ldap
    --force
  when: ansible_os_family == 'Debian'
